---
title: "Example1-2"
output: html_document
---

```{r setup, include=FALSE}
setwd('Z:/User/Documents/dynamic weighted network LSM/Simulation')
.libPaths('Z:/User/Documents/R/win-library/4.1')
```

```{r, warning=FALSE}
library(tidyverse)
library(ggpubr)
library(parallel)
library(foreach)
library(doParallel)
library(RSpectra)
clnum <- detectCores()
cl <- makeCluster(clnum)  
registerDoParallel(cl) 
print(clnum)
```

## Initialization

```{r}
init.func <- function(N, D, Ti, node.exist, seed){
  set.seed(seed)
  alpha <- runif(N, -2, -1)
  beta <- runif(Ti, -1, 1)
  Z <- list()
  for (t in 1:Ti) {
    Nt <- node.exist.num[t]
    Jmat <- diag(rep(1,Nt)) - matrix(1, Nt, Nt)/Nt
    Z0 <- matrix(runif(Nt*D, -0.5, 0.5), Nt, D)
    Z0 <- Jmat%*%Z0
    Z0 <- qr.Q(qr(Z0))
    Z0 <- Z0*sqrt(Nt*D/1)/norm(Z0,'F')
    Z[[t]] <- Z0 
  }
  return(list(Z=Z, alpha=alpha, beta=beta)) 
}
```

## Optimization

```{r}
opt.func <- function(Z.ini, alpha.ini, beta.ini, A, X, node.exist, nu=0.5, step.size=0.2, epsi=0.0005, niter=500, trace=0){
  
  N <- length(alpha.ini)
  Ti <- length(beta.ini)
  D <- dim(Z.ini[[1]])[2]
  
  # step size
  step.size.z <- step.size/(Ti*N*D)
  step.size.alpha <- step.size/(Ti*N)
  step.size.beta <- step.size/sum(unlist(lapply(1:Ti, function(t) norm(X[[t]],'F')^2)))
  
  diff <- 1
  iter <- 0
  obj <- -Inf
  
  Z <- list()
  alpha <- rep(NA, N)
  beta <- rep(NA, Ti)
  
  while (diff>epsi & iter<niter) {
    Theta.hat <- lapply(1:Ti, function(t) alpha.ini[node.exist[[t]]] %*% t(rep(1,length(node.exist[[t]]))) + 
                          rep(1,length(node.exist[[t]])) %*% t(alpha.ini[node.exist[[t]]]) + 
                          Z.ini[[t]] %*% t(Z.ini[[t]]) + beta.ini[t]*X[[t]])
    
    obj1 <- lapply(1:Ti, function(t) (A[[t]] * Theta.hat[[t]] - exp(Theta.hat[[t]])) * 
                     (matrix(rep(1, length(node.exist[[t]])), length(node.exist[[t]]), length(node.exist[[t]])) - 
                        diag(1, length(node.exist[[t]]), length(node.exist[[t]]))))
    tmp.obj <- sum(unlist(lapply(1:Ti, function(t) sum(obj1[[t]]))))
    obj <- c(obj,tmp.obj)
    if(trace==1){
      print(iter)
      print(diff)
      print(tmp.obj)
    }
    
    if(obj[length(obj)] < obj[length(obj)-1]){
      step.size.z <- step.size.z * nu
      step.size.alpha <- step.size.alpha * nu
      step.size.beta <- step.size.beta * nu
    }
    
    alpha.grad <- rep(0, N)
    for (t in 1:Ti) {
      Nt <- length(node.exist[[t]])
      Theta.t <- alpha.ini[node.exist[[t]]] %*% t(rep(1,Nt)) + 
        rep(1,Nt) %*% t(alpha.ini[node.exist[[t]]]) + 
        Z.ini[[t]] %*% t(Z.ini[[t]]) + beta.ini[t]*X[[t]]
 
      Omega.t <- A[[t]] - exp(Theta.t)
      Omega.t[Omega.t>2] <- 2  
      Omega.t[Omega.t<-2] <- -2  
      diag(Omega.t) <- 0
      
      Z.grad <- 2 * Omega.t %*% Z.ini[[t]]
      alpha.grad[node.exist[[t]]] <- alpha.grad[node.exist[[t]]] + 2 * Omega.t %*% rep(1,Nt)
      beta.grad <- sum(Omega.t * X[[t]])

      
      Z[[t]] <- Z.ini[[t]] + step.size.z * Z.grad
      Jmat <- diag(rep(1,Nt)) - matrix(1, Nt, Nt)/Nt
      Z[[t]] <- Jmat %*% Z[[t]]
      Z[[t]] <- qr.Q(qr(Z[[t]]))
      Z[[t]] <- Z[[t]]*sqrt(Nt*D/1)/norm(Z[[t]],'F')
      
      beta[t] <- beta.ini[t] + step.size.beta * beta.grad

    }
    alpha <- alpha.ini + step.size.alpha * alpha.grad
    
    Z.diff.list <- c()
    for (t in 1:Ti) {
      dec <- svd(t(Z[[t]]) %*% Z.ini[[t]])
      O <- dec$v %*% t(dec$u)
      re0 <- norm(Z[[t]] - Z.ini[[t]] %*% O,'F')^2 
      Z.diff.list <- c(Z.diff.list, re0)
    }
    Z.diff <- sum(Z.diff.list)/sum(unlist(lapply(1:Ti, function(t) norm(Z.ini[[t]],'F')^2)))
    
    alpha.diff <- sum((alpha-alpha.ini)^2)/sum(alpha.ini^2)
    beta.diff <- sum((beta-beta.ini)^2)/sum(beta.ini^2)
    
    diff <- max(Z.diff, alpha.diff, beta.diff)
    
    iter <- iter+1
    
    # update
    Z.ini <- Z
    alpha.ini <- alpha
    beta.ini <- beta
  }
  
  Theta.hat <- lapply(1:Ti, function(t) alpha[node.exist[[t]]] %*% t(rep(1,length(node.exist[[t]]))) + rep(1,length(node.exist[[t]])) %*% t(alpha[node.exist[[t]]]) + Z[[t]] %*% t(Z[[t]]) + beta[t]*X[[t]])
  obj1 <- lapply(1:Ti, function(t) (A[[t]] * Theta.hat[[t]] - exp(Theta.hat[[t]])) * (matrix(rep(1, length(node.exist[[t]])*length(node.exist[[t]])), length(node.exist[[t]]), length(node.exist[[t]])) - diag(1, length(node.exist[[t]]), length(node.exist[[t]]))))
  tmp.obj <- sum(unlist(lapply(1:Ti, function(t) sum(obj1[[t]]))))
  obj <- c(obj, tmp.obj)
  

  if (iter==niter)
  {cat("Warning! May Not Convergence", "\n")}
  cat("Number of iterations=",iter,"\n")
  cat("The objective value=",tmp.obj,"\n")
  
  return(list(params=list(Z=Z, alpha=alpha, beta=beta), Theta=Theta.hat, obj=obj, iter=iter))                    
                      
}
```

## Main function

```{r}
main.func <- function(Z.true, alpha.true, beta.true, node.exist, nu, eta, delta, step.size=0.2, epsi=0.00001, niter=500, trace=0, seed=10){
  
  N <- length(alpha.true)
  Ti <- length(beta.true)
  D <- dim(Z.true[[1]])[2]
  
  set.seed(seed)
  
  X <- list()
  for (t in 1:Ti) {
    Nt <- length(node.exist[[t]])
    Xt0 <- matrix(runif(Nt * (6*D), -0.5, 0.5), Nt, (6*D))
    Xt <- Xt0 %*% t(Xt0)
    X[[t]] <- Xt
  }
  
  A <- list()
  
  Theta.true <- list()
  Lambda.true <- list()
  for (t in 1:Ti) {
    Nt <- length(node.exist[[t]])
    Theta.true[[t]] <- alpha.true[node.exist[[t]]] %*% t(rep(1,Nt)) + rep(1,Nt) %*% t(alpha.true[node.exist[[t]]]) + Z.true[[t]] %*% t(Z.true[[t]]) + beta.true[t]*X[[t]]
    Lambda.true[[t]] <- exp(Theta.true[[t]])
    gen.A <- apply(Lambda.true[[t]], 1:2, function(x) rpois(1, x))
    gen.A[lower.tri(gen.A, diag = TRUE)] <- 0
    A[[t]] <- gen.A + t(gen.A)  
  }
  max.weight <- max(unlist(A))
  
  para.ini <- init.func(N, D, Ti, node.exist, seed=seed)
  Z.ini <- para.ini$Z
  alpha.ini <- para.ini$alpha
  beta.ini <- para.ini$beta

  start_time1 <- proc.time()
  result <- opt.func(Z.ini, alpha.ini, beta.ini, A, X, node.exist, nu=nu, step.size=step.size, epsi=epsi, niter=niter, trace=trace)
  end_time1 <- proc.time() 
  time1 <- end_time1 - start_time1 
  time1 <- time1[3][[1]]/result$iter
  
  Theta.relative.error <- sum(unlist(lapply(1:Ti, function(t) norm(result$Theta[[t]]-Theta.true[[t]],'F')^2)))/sum(unlist(lapply(1:Ti, function(t) norm(Theta.true[[t]],'F')^2)))
  Theta.error <- sum(unlist(lapply(1:Ti, function(t) norm(result$Theta[[t]]-Theta.true[[t]],'F')^2)))/(N^2)
  obj <- result$obj[length(result$obj)]
  iter <- result$iter

  return(c(N,Ti,D,max.weight,
           Theta.relative.error,Theta.error,
           obj,iter,time1))
}

```


## Start example 1

```{r}
N.set <- c(100,150,200,250,300,350,400,500,800)
Ti <- 10
D <- 2
set.seed(12)
rho <- c(sort(runif(Ti-1, 0.6, 1)),1)  # The proportion of keywords in each time period relative to the total keywords.
rho

nsim <- 100

bingo.N <- data.frame(matrix(nrow=0, ncol=9))
colnames(bingo.N) <- c('N','Ti','D','max.weight',
                     'Theta.relative.error','Theta.error',
                     'obj','iter','time1')

for (u in 1:length(N.set)) {
  set.seed(u) 
  N <- N.set[u]
  print(N)
  # nodes at each time
  node.exist.num <- ceiling(N * rho)
  node.exist <- lapply(1:Ti, function(t) sort(sample(N, node.exist.num[t], replace = FALSE)))
  
  # true value
  Z.true <- list()
  for (t in 1:Ti) {
    Nt <- node.exist.num[t]
    Jmat <- diag(rep(1,Nt)) - matrix(1, Nt, Nt)/Nt
    Z.true0 <- matrix(runif(Nt*D, -0.5, 0.5), Nt, D)
    Z.true0 <- Jmat%*%Z.true0
    Z.true0 <- qr.Q(qr(Z.true0))
    Z.true0 <- Z.true0*sqrt(Nt*D/1)/norm(Z.true0,'F')
    Z.true[[t]] <- Z.true0 
  }
  alpha.true <- runif(N, -3, -1)
  beta.true <- runif(Ti, -3, 3)
  
  result0 <- foreach(r=1:nsim, .combine=rbind, .packages=c('irlba'))  %dopar%
    {
      .libPaths('Z:/User/Documents/R/win-library/4.1')
      # install.packages('RSpectra')
      library(RSpectra)
      tryCatch({
        main.func(Z.true, alpha.true, beta.true, node.exist, nu=0.6, eta=1/(N), delta=1/(N), step.size=5, epsi=0.00001, niter=500, trace=0, seed=r*u)
      },
      warning = function(w){cat("WARNING :",conditionMessage(w), "\n")},
      error = function(e){cat("ERROR :",conditionMessage(e), "\n")}
      )
    }
  colnames(result0) <- c('N','Ti','D','max.weight',
                         'Theta.relative.error','Theta.error',
                         'obj','iter','time1')
  
  bingo.N <- rbind(bingo.N, result0)
  
}
```

## Draw boxplot

```{r}
d1.1 <- bingo.N
d1.1$N <- as.factor(d1.1$N)

g1.1 <- ggplot(d1.1, aes(x=N, y=Theta.relative.error)) + 
  geom_boxplot() +
  labs(y = "Relative error", x='Number of nodes')+   #改变坐标名称
  theme_bw()+
  theme(axis.text.x = element_text(size=20),
        axis.text.y = element_text(size=20),
        axis.title.y = element_text(size=30),
        axis.title.x = element_text(size=30),
        text=element_text(family="serif"))
g1.1
```


## Start example 2

```{r}
N <- 200
Ti <- 10
D.set <- seq(1,10)

set.seed(12)
rho <- c(sort(runif(Ti-1, 0.6, 1)),1)  # The proportion of keywords in each time period relative to the total keywords.
rho

nsim <- 100

bingo.d <- data.frame(matrix(nrow=0, ncol=9))
colnames(bingo.d) <- c('N','Ti','D','max.weight',
                     'Theta.relative.error','Theta.error',
                     'obj','iter','time1')

for (u in 1:length(D.set)) {
  set.seed(u) 
  D <- D.set[u]
  print(D)
  # nodes at each time
  node.exist.num <- ceiling(N * rho)
  node.exist <- lapply(1:Ti, function(t) sort(sample(N, node.exist.num[t], replace = FALSE)))
  
  # true value
  Z.true <- list()
  for (t in 1:Ti) {
    Nt <- node.exist.num[t]
    Jmat <- diag(rep(1,Nt)) - matrix(1, Nt, Nt)/Nt
    Z.true0 <- matrix(runif(Nt*D, -0.5, 0.5), Nt, D)
    Z.true0 <- Jmat%*%Z.true0
    Z.true0 <- qr.Q(qr(Z.true0))
    Z.true0 <- Z.true0*sqrt(Nt*D/1)/norm(Z.true0,'F')
    Z.true[[t]] <- Z.true0 
  }
  alpha.true <- runif(N, -3, -1)
  beta.true <- runif(Ti, -3, 3)

  
  result0 <- foreach(r=1:nsim, .combine=rbind, .packages=c('irlba'))  %dopar%
    {
      .libPaths('Z:/User/Documents/R/win-library/4.1')
      # install.packages('RSpectra')
      library(RSpectra)
      tryCatch({
        main.func(Z.true, alpha.true, beta.true, node.exist, nu=0.6, eta=1/(N), delta=1/(N), step.size=5, epsi=0.00001, niter=500, trace=0, seed=r*u)
      },
      warning = function(w){cat("WARNING :",conditionMessage(w), "\n")},
      error = function(e){cat("ERROR :",conditionMessage(e), "\n")}
      )
    }
  colnames(result0) <- c('N','Ti','D','max.weight',
                         'Theta.relative.error','Theta.error',
                         'obj','iter','time1')
  
  bingo.d <- rbind(bingo.d, result0)
  
}

```

## Draw boxplot

```{r}
d1.2 <- bingo.d
d1.2 <- d1.2[d1.2$Theta.relative.error<=1,]
d1.2$D <- as.factor(d1.2$D)

g1.2 <- ggplot(d1.2, aes(x=D, y=Theta.relative.error)) + 
  geom_boxplot() +
  labs(y = "Relative error", x='Dimension of latent variables')+   #改变坐标名称
  theme_bw()+
  theme(axis.text.x = element_text(size=20),
        axis.text.y = element_text(size=20),
        axis.title.y = element_text(size=30),
        axis.title.x = element_text(size=30),
        text=element_text(family="serif"))
g1.2

ggarrange(g1.1, g1.2, labels = c("(a)","(b)"),widths = c(2,2), ncol =2, nrow = 1)
ggsave('simulation-results1.pdf', width = 20, height = 8)

```